sudo: required
services:
  - docker

before_install:
  - docker build -t ovararu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ovararu/react-test npm test -- --coverage

after_success:
  - docker build -t ovararu/multi-client ./client
  - docker build -t ovararu/multi-nginx ./nginx
  - docker build -t ovararu/multi-server ./server
  - docker build -t ovararu/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # Take those images and push them to the docker hub
  - docker push ovararu/multi-client
  - docker push ovararu/multi-nginx
  - docker push ovararu/multi-server
  - docker push ovararu/multi-worker
  
